site_name: Incident.io Python Client
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - toc.follow
strict: true
repo_name: expobrain/python-incidentio-client"
repo_url: https://github.com/expobrain/python-incidentio-client
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Overview: index.md
  - API Reference:
      - client: api_reference/client.md
      - types: api_reference/types.md
      - api:
          - actions_v1:
              - actions_v1_list: api_reference/api/actions_v1/actions_v1_list.md
              - actions_v1_show: api_reference/api/actions_v1/actions_v1_show.md
          - custom_field_options_v1:
              - custom_field_options_v1_create: api_reference/api/custom_field_options_v1/custom_field_options_v1_create.md
              - custom_field_options_v1_delete: api_reference/api/custom_field_options_v1/custom_field_options_v1_delete.md
              - custom_field_options_v1_list: api_reference/api/custom_field_options_v1/custom_field_options_v1_list.md
              - custom_field_options_v1_show: api_reference/api/custom_field_options_v1/custom_field_options_v1_show.md
              - custom_field_options_v1_update: api_reference/api/custom_field_options_v1/custom_field_options_v1_update.md
          - custom_fields_v1:
              - custom_fields_v1_create: api_reference/api/custom_fields_v1/custom_fields_v1_create.md
              - custom_fields_v1_delete: api_reference/api/custom_fields_v1/custom_fields_v1_delete.md
              - custom_fields_v1_list: api_reference/api/custom_fields_v1/custom_fields_v1_list.md
              - custom_fields_v1_show: api_reference/api/custom_fields_v1/custom_fields_v1_show.md
              - custom_fields_v1_update: api_reference/api/custom_fields_v1/custom_fields_v1_update.md
          - incident_attachments_v1:
              - incident_attachments_v1_create: api_reference/api/incident_attachments_v1/incident_attachments_v1_create.md
              - incident_attachments_v1_delete: api_reference/api/incident_attachments_v1/incident_attachments_v1_delete.md
              - incident_attachments_v1_list: api_reference/api/incident_attachments_v1/incident_attachments_v1_list.md
          - incident_roles_v1:
              - incident_roles_v1_create: api_reference/api/incident_roles_v1/incident_roles_v1_create.md
              - incident_roles_v1_delete: api_reference/api/incident_roles_v1/incident_roles_v1_delete.md
              - incident_roles_v1_list: api_reference/api/incident_roles_v1/incident_roles_v1_list.md
              - incident_roles_v1_show: api_reference/api/incident_roles_v1/incident_roles_v1_show.md
              - incident_roles_v1_update: api_reference/api/incident_roles_v1/incident_roles_v1_update.md
          - incident_types_v1:
              - incident_types_v1_list: api_reference/api/incident_types_v1/incident_types_v1_list.md
              - incident_types_v1_show: api_reference/api/incident_types_v1/incident_types_v1_show.md
          - incidents_v1:
              - incidents_v1_create: api_reference/api/incidents_v1/incidents_v1_create.md
              - incidents_v1_list: api_reference/api/incidents_v1/incidents_v1_list.md
              - incidents_v1_show: api_reference/api/incidents_v1/incidents_v1_show.md
          - incidents_v2:
              - incidents_v2_create: api_reference/api/incidents_v2/incidents_v2_create.md
              - incidents_v2_list: api_reference/api/incidents_v2/incidents_v2_list.md
              - incidents_v2_show: api_reference/api/incidents_v2/incidents_v2_show.md
          - severities_v1:
              - severities_v1_create: api_reference/api/severities_v1/severities_v1_create.md
              - severities_v1_delete: api_reference/api/severities_v1/severities_v1_delete.md
              - severities_v1_list: api_reference/api/severities_v1/severities_v1_list.md
              - severities_v1_show: api_reference/api/severities_v1/severities_v1_show.md
              - severities_v1_update: api_reference/api/severities_v1/severities_v1_update.md
          - utilities_v1:
              - utilities_v1_identity: api_reference/api/utilities_v1/utilities_v1_identity.md
              - utilities_v1_open_api: api_reference/api/utilities_v1/utilities_v1_open_api.md
      - models:
          - action_v1_response_body: api_reference/models/action_v1_response_body.md
          - action_v1_response_body_status: api_reference/models/action_v1_response_body_status.md
          - actions_v1_list_incident_mode: api_reference/models/actions_v1_list_incident_mode.md
          - actions_v1_list_response_body: api_reference/models/actions_v1_list_response_body.md
          - actions_v1_show_response_body: api_reference/models/actions_v1_show_response_body.md
          - actor_v1_response_body: api_reference/models/actor_v1_response_body.md
          - actor_v2_response_body: api_reference/models/actor_v2_response_body.md
          - api_key_v1_response_body: api_reference/models/api_key_v1_response_body.md
          - api_key_v2_response_body: api_reference/models/api_key_v2_response_body.md
          - custom_field_entry_payload_v1_request_body: api_reference/models/custom_field_entry_payload_v1_request_body.md
          - custom_field_entry_payload_v2_request_body: api_reference/models/custom_field_entry_payload_v2_request_body.md
          - custom_field_entry_v1_response_body: api_reference/models/custom_field_entry_v1_response_body.md
          - custom_field_entry_v2_response_body: api_reference/models/custom_field_entry_v2_response_body.md
          - custom_field_option_v1_response_body: api_reference/models/custom_field_option_v1_response_body.md
          - custom_field_option_v2_response_body: api_reference/models/custom_field_option_v2_response_body.md
          - custom_field_options_v1_create_request_body: api_reference/models/custom_field_options_v1_create_request_body.md
          - custom_field_options_v1_create_response_body: api_reference/models/custom_field_options_v1_create_response_body.md
          - custom_field_options_v1_list_response_body: api_reference/models/custom_field_options_v1_list_response_body.md
          - custom_field_options_v1_show_response_body: api_reference/models/custom_field_options_v1_show_response_body.md
          - custom_field_options_v1_update_request_body: api_reference/models/custom_field_options_v1_update_request_body.md
          - custom_field_options_v1_update_response_body: api_reference/models/custom_field_options_v1_update_response_body.md
          - custom_field_type_info_v1_response_body: api_reference/models/custom_field_type_info_v1_response_body.md
          - custom_field_type_info_v1_response_body_field_type: api_reference/models/custom_field_type_info_v1_response_body_field_type.md
          - custom_field_type_info_v2_response_body: api_reference/models/custom_field_type_info_v2_response_body.md
          - custom_field_type_info_v2_response_body_field_type: api_reference/models/custom_field_type_info_v2_response_body_field_type.md
          - custom_field_v1_response_body: api_reference/models/custom_field_v1_response_body.md
          - custom_field_v1_response_body_field_type: api_reference/models/custom_field_v1_response_body_field_type.md
          - custom_field_v1_response_body_required: api_reference/models/custom_field_v1_response_body_required.md
          - custom_field_value_payload_v1_request_body: api_reference/models/custom_field_value_payload_v1_request_body.md
          - custom_field_value_payload_v2_request_body: api_reference/models/custom_field_value_payload_v2_request_body.md
          - custom_field_value_v1_response_body: api_reference/models/custom_field_value_v1_response_body.md
          - custom_field_value_v2_response_body: api_reference/models/custom_field_value_v2_response_body.md
          - custom_fields_v1_create_request_body: api_reference/models/custom_fields_v1_create_request_body.md
          - custom_fields_v1_create_request_body_field_type: api_reference/models/custom_fields_v1_create_request_body_field_type.md
          - custom_fields_v1_create_request_body_required: api_reference/models/custom_fields_v1_create_request_body_required.md
          - custom_fields_v1_create_response_body: api_reference/models/custom_fields_v1_create_response_body.md
          - custom_fields_v1_list_response_body: api_reference/models/custom_fields_v1_list_response_body.md
          - custom_fields_v1_show_response_body: api_reference/models/custom_fields_v1_show_response_body.md
          - custom_fields_v1_update_request_body: api_reference/models/custom_fields_v1_update_request_body.md
          - custom_fields_v1_update_request_body_required: api_reference/models/custom_fields_v1_update_request_body_required.md
          - custom_fields_v1_update_response_body: api_reference/models/custom_fields_v1_update_response_body.md
          - external_issue_reference_v1_response_body: api_reference/models/external_issue_reference_v1_response_body.md
          - external_resource_v1_response_body: api_reference/models/external_resource_v1_response_body.md
          - external_resource_v1_response_body_resource_type: api_reference/models/external_resource_v1_response_body_resource_type.md
          - identity_v1_response_body: api_reference/models/identity_v1_response_body.md
          - identity_v1_response_body_roles_item: api_reference/models/identity_v1_response_body_roles_item.md
          - incident_attachment_v1_response_body: api_reference/models/incident_attachment_v1_response_body.md
          - incident_attachments_v1_create_request_body: api_reference/models/incident_attachments_v1_create_request_body.md
          - incident_attachments_v1_create_request_body_resource: api_reference/models/incident_attachments_v1_create_request_body_resource.md
          - incident_attachments_v1_create_request_body_resource_resource_type: api_reference/models/incident_attachments_v1_create_request_body_resource_resource_type.md
          - incident_attachments_v1_create_response_body: api_reference/models/incident_attachments_v1_create_response_body.md
          - incident_attachments_v1_list_resource_type: api_reference/models/incident_attachments_v1_list_resource_type.md
          - incident_attachments_v1_list_response_body: api_reference/models/incident_attachments_v1_list_response_body.md
          - incident_role_assignment_payload_v1_request_body: api_reference/models/incident_role_assignment_payload_v1_request_body.md
          - incident_role_assignment_payload_v2_request_body: api_reference/models/incident_role_assignment_payload_v2_request_body.md
          - incident_role_assignment_v1_response_body: api_reference/models/incident_role_assignment_v1_response_body.md
          - incident_role_assignment_v2_response_body: api_reference/models/incident_role_assignment_v2_response_body.md
          - incident_role_v1_response_body: api_reference/models/incident_role_v1_response_body.md
          - incident_role_v1_response_body_role_type: api_reference/models/incident_role_v1_response_body_role_type.md
          - incident_role_v2_response_body: api_reference/models/incident_role_v2_response_body.md
          - incident_role_v2_response_body_role_type: api_reference/models/incident_role_v2_response_body_role_type.md
          - incident_roles_v1_create_request_body: api_reference/models/incident_roles_v1_create_request_body.md
          - incident_roles_v1_create_response_body: api_reference/models/incident_roles_v1_create_response_body.md
          - incident_roles_v1_list_response_body: api_reference/models/incident_roles_v1_list_response_body.md
          - incident_roles_v1_show_response_body: api_reference/models/incident_roles_v1_show_response_body.md
          - incident_roles_v1_update_request_body: api_reference/models/incident_roles_v1_update_request_body.md
          - incident_roles_v1_update_response_body: api_reference/models/incident_roles_v1_update_response_body.md
          - incident_status_v2_response_body: api_reference/models/incident_status_v2_response_body.md
          - incident_status_v2_response_body_category: api_reference/models/incident_status_v2_response_body_category.md
          - incident_timestamp_v1_response_body: api_reference/models/incident_timestamp_v1_response_body.md
          - incident_timestamp_v2_response_body: api_reference/models/incident_timestamp_v2_response_body.md
          - incident_timestamp_v2_response_body_required: api_reference/models/incident_timestamp_v2_response_body_required.md
          - incident_timestamp_v2_response_body_set_on_transition: api_reference/models/incident_timestamp_v2_response_body_set_on_transition.md
          - incident_timestamp_v2_response_body_set_on_visit: api_reference/models/incident_timestamp_v2_response_body_set_on_visit.md
          - incident_timestamp_value_payload_v2_request_body: api_reference/models/incident_timestamp_value_payload_v2_request_body.md
          - incident_timestamp_value_v2_response_body: api_reference/models/incident_timestamp_value_v2_response_body.md
          - incident_timestamp_with_value_v2_response_body: api_reference/models/incident_timestamp_with_value_v2_response_body.md
          - incident_type_v1_response_body: api_reference/models/incident_type_v1_response_body.md
          - incident_type_v2_response_body: api_reference/models/incident_type_v2_response_body.md
          - incident_types_v1_list_response_body: api_reference/models/incident_types_v1_list_response_body.md
          - incident_types_v1_show_response_body: api_reference/models/incident_types_v1_show_response_body.md
          - incident_v1_response_body: api_reference/models/incident_v1_response_body.md
          - incident_v1_response_body_mode: api_reference/models/incident_v1_response_body_mode.md
          - incident_v1_response_body_status: api_reference/models/incident_v1_response_body_status.md
          - incident_v1_response_body_visibility: api_reference/models/incident_v1_response_body_visibility.md
          - incident_v2_response_body: api_reference/models/incident_v2_response_body.md
          - incident_v2_response_body_mode: api_reference/models/incident_v2_response_body_mode.md
          - incident_v2_response_body_visibility: api_reference/models/incident_v2_response_body_visibility.md
          - incidents_v1_create_request_body: api_reference/models/incidents_v1_create_request_body.md
          - incidents_v1_create_request_body_mode: api_reference/models/incidents_v1_create_request_body_mode.md
          - incidents_v1_create_request_body_status: api_reference/models/incidents_v1_create_request_body_status.md
          - incidents_v1_create_request_body_visibility: api_reference/models/incidents_v1_create_request_body_visibility.md
          - incidents_v1_create_response_body: api_reference/models/incidents_v1_create_response_body.md
          - incidents_v1_list_response_body: api_reference/models/incidents_v1_list_response_body.md
          - incidents_v1_show_response_body: api_reference/models/incidents_v1_show_response_body.md
          - incidents_v2_create_request_body: api_reference/models/incidents_v2_create_request_body.md
          - incidents_v2_create_request_body_mode: api_reference/models/incidents_v2_create_request_body_mode.md
          - incidents_v2_create_request_body_visibility: api_reference/models/incidents_v2_create_request_body_visibility.md
          - incidents_v2_create_response_body: api_reference/models/incidents_v2_create_response_body.md
          - incidents_v2_list_response_body: api_reference/models/incidents_v2_list_response_body.md
          - incidents_v2_show_response_body: api_reference/models/incidents_v2_show_response_body.md
          - pagination_meta_response_body: api_reference/models/pagination_meta_response_body.md
          - severities_v1_create_request_body: api_reference/models/severities_v1_create_request_body.md
          - severities_v1_create_response_body: api_reference/models/severities_v1_create_response_body.md
          - severities_v1_list_response_body: api_reference/models/severities_v1_list_response_body.md
          - severities_v1_show_response_body: api_reference/models/severities_v1_show_response_body.md
          - severities_v1_update_request_body: api_reference/models/severities_v1_update_request_body.md
          - severities_v1_update_response_body: api_reference/models/severities_v1_update_response_body.md
          - severity_v1_response_body: api_reference/models/severity_v1_response_body.md
          - severity_v2_response_body: api_reference/models/severity_v2_response_body.md
          - user_reference_payload_v1_request_body: api_reference/models/user_reference_payload_v1_request_body.md
          - user_reference_payload_v2_request_body: api_reference/models/user_reference_payload_v2_request_body.md
          - user_v1_response_body: api_reference/models/user_v1_response_body.md
          - user_v1_response_body_role: api_reference/models/user_v1_response_body_role.md
          - user_v2_response_body: api_reference/models/user_v2_response_body.md
          - user_v2_response_body_role: api_reference/models/user_v2_response_body_role.md
          - utilities_v1_identity_response_body: api_reference/models/utilities_v1_identity_response_body.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_signature_annotations: true
            separate_signature: true
