name: Checks that OpenAPI specs are up to date
on: [push]
  # schedule:
  #   - cron: "0 0 * * *"
jobs:
  check-openapi-spec-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make download
      - uses: tj-actions/verify-changed-files@v9.1
        id: verify-changed-openapi-specs
        with:
          files: incidentio_openapi.yaml
      - uses: actions/setup-python@v2
        if: steps.verify-changed-openapi-specs.outputs.files_changed == 'true'
        with:
          python-version: "3.10"
      - name: Cache Pip
        if: steps.verify-changed-openapi-specs.outputs.files_changed == 'true'
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-3.10-${{ hashFiles('**/poetry.lock') }}
      - if: steps.verify-changed-openapi-specs.outputs.files_changed == 'true'
        run: |
          pip install poetry
          poetry install
          poetry run make generate
          git add incident_io_openapi.json incident_io_client
          gh pr create --title "Updated API at $(date "+%Y-%m-%d")"
