name: Upload Python Package

env:
  PYTHON_VERSION_FOR_PACKAGING: "3.11"
  POETRY_VERSION: "1.3"

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  publish_package:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION_FOR_PACKAGING }}"
      - name: Cache Pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-${{ env.PYTHON_VERSION_FOR_PACKAGING }}-${{ hashFiles('**/poetry.lock') }}
      - run: pip install poetry~=${{ env.POETRY_VERSION }}
      - run: poetry build
      # From https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#publishing-the-distribution-to-pypi-and-testpypi
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.12
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
